# Generated by Django 3.2.16 on 2023-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230410_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='expertise',
            field=models.CharField(max_length=30, verbose_name='Skill level'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of subject'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='expertise',
            field=models.CharField(max_length=30, verbose_name='Skill level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of subject'),
        ),
    ]
