# Generated by Django 3.2.16 on 2023-04-10 19:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0009_auto_20230410_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=30, verbose_name='Name of subject')),
                ('expertise', models.CharField(max_length=30, verbose_name='Skill level')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='interest',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.CreateModel(
            name='TaggedWhatever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_taggedwhatever_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_taggedwhatever_items', to='users.mycustomtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interest',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='users.TaggedWhatever', to='users.MyCustomTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='users.TaggedWhatever', to='users.MyCustomTag', verbose_name='Tags'),
        ),
    ]
