# Generated by Django 3.2.16 on 2023-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='formula',
            field=models.CharField(default='0', max_length=100, verbose_name='Mathematical weight formula'),
        ),
    ]
