# Generated by Django 3.2.16 on 2023-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_weight_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='formula',
            field=models.CharField(default='1', max_length=100, verbose_name='Mathematical weight formula'),
        ),
    ]
