# Generated by Django 3.2.16 on 2023-05-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230522_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to='users.Project'),
        ),
    ]
